### ISSUE TITLE
State structure

### ISSUE THREAD

**Issue by r00bal** [KamilSzafranski/goit-react-hw-03-image-finder#1]
https://github.com/KamilSzafranski/goit-react-hw-03-image-finder/blob/84417d7ca011b10200a1068547258cdd8c999aa9/src/components/Gallery/Gallery.jsx#L102-L103

Czy napewno potrzebujesz tyle danych pchać do stanu, tym bardziej, że to są i tak dane, które masz już w stanie w gallery dla każdego elementu. Myślę, że lepiej by się sprawdziło coś w stylu przechowywania id aktywnego elementu. Na podstawie tego id później na bierząco możesz złapać element do modala a nawet stworzyć warunek kiedy modal ma się pojawić i stosować zamiast  `isModalOpen`. To znacznie mogłoby uprościć stan komponentu.
Tu jest fajne opisane co wrzucać do stanu:
https://beta.reactjs.org/learn/choosing-the-state-structure

**Comment by KamilSzafranski** [comment]
poprawione :)
